### ISSUE TITLE
java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by duncte123** [jagrosh/JagTag#1]
When using the following syntax I get a stack trace like the one below it.
```perl
{if:{argslen}|<|3|then:Please supply 4 words|else:Your 3rd word was: {arg:2}}
```

```prolog
java.lang.ArithmeticException: / by zero
	at com.jagrosh.jagtag.libraries.Arguments.lambda$getMethods$2(Arguments.java:67)
	at com.jagrosh.jagtag.Method.parseComplex(Method.java:161)
	at com.jagrosh.jagtag.Parser.parse(Parser.java:118)
	at ml.duncte123.skybot.CommandManager.dispatchCommand(CommandManager.java:300)
	at ml.duncte123.skybot.CommandManager.dispatchCommand(CommandManager.java:278)
	at ml.duncte123.skybot.CommandManager.runCommand(CommandManager.java:270)
	at ml.duncte123.skybot.BotListener.onGuildMessageReceived(BotListener.java:270)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:380)
	at ml.duncte123.skybot.EventManager.handle(EventManager.java:69)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:95)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:999)
	at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:904)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:883)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1037)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

The arguments supplied are:<br>
user: JDA User
channel: JDA TextChannel
guild: JDA Guill
splitargs: String[]
args: splitargs joined with `|` as separator

**Comment by jagrosh** [comment]
You should not be supplying the `splitargs`, the environment only expects a single string supplied as `args`.
Edit: You _can_ provide the user, channel, guild, etc. Just don't supply `splitargs`, as an empty array is not handled (nor is intended to be handled).

**Comment by duncte123** [comment]
Thanks that fixed it, thanks
